### ISSUE TITLE
Gotta Go Fast

### ISSUE THREAD

**Issue by ConnorNelson** [pwncollege/dojo#112]
Obviously we need to seriously optimize whatever is taking pages multiple seconds to load (likely something is terribly non-optimal with our dojo querying).

We should also take advantage of prefetch and prerender though.

Incredible click-bait: https://ipullrank.com/how-i-sped-up-my-site-68-percent-with-one-line-of-code

**Comment by Scoder12** [comment]
I think that article is about client-side performance
The first step might be some profiling: https://dev.to/yellalena/profiling-flask-application-to-improve-performance-4970
My guess would be that challenge starts are blocking the process from responding to requests (#83)
