### ISSUE TITLE
Fix Ghidra

### ISSUE THREAD

**Issue by ConnorNelson** [pwncollege/dojo#121]
ghidra decompilation fails with permission denied and the icon is broken

**Comment by zardus** [comment]
The switch to jar from unzip destroyed permissions. I fixed it for the main launch, but apparently didn’t test the whole thing.We should just switch back to unzip, IMOOn Jan 4, 2023, at 6:05 PM, Connor Nelson ***@***.***> wrote:﻿
ghidra decompilation fails with permission denied and the icon is broken
