### ISSUE TITLE
README.md revision to make dojo installation clear

### ISSUE THREAD

**Issue by mudongliang** [pwncollege/dojo#145]
It seems the private instance dojo is installed with `docker compose up`, other than the script `run.sh` mentioned in README.md. Maybe there needs some revision about the README installation.

Newbie for pwn college. Will adopt it in our teaching class - Software Security.

**Comment by ConnorNelson** [comment]
Our README should now be accurate.
That being said, we should add CI to make sure it continues to be accurate. I will close this in favor of #126 for tracking that.
