### ISSUE TITLE
IRC bridge?

### ISSUE THREAD

**Issue by zardus** [pwncollege/dojo#147]
I've gotten a request for an IRC bridge twice in as many days. Even though I literally teach IRC as literal history now, people still love the classics.

Maybe we should set up an IRC bridge? Seems pretty simple to integrate: https://github.com/42wim/matterbridge/wiki/Deploy:-Docker

**Comment by zardus** [comment]
Caveats here are how to handle:

- abuse and bans (do we just shut down the IRC bridge the first time it gets abused?)
- inevitable requests to get extra credit for help provided over IRC

These issues might not be surmountable. As a halfway point, though, we could make IRC read-only for most of the discord, with maybe a single read/write chaotic-shitshow channel? Or maybe just read-only.

**Comment by zardus** [comment]
One idea: the IRC part of the bridge doesn't have to be open to everyone. We could manually approve access one a case-by-case basis (since we've had just a handful of requests in the history of pwn.college, this should be doable), and revoke them if things go haywire.

**Comment by ConnorNelson** [comment]
No
