### ISSUE TITLE
Bug? - Updating Topic Content does not update course content

### ISSUE THREAD

**Issue by robwaz** [pwncollege/dojo#163]
Current course content is re-imported when current course repo is updated.

 Updating a topic's repo does not trigger a re-import for any current courses that may rely on it.   This isn't a deal-breaker.  Might not be an expected use-case.

**Comment by ConnorNelson** [comment]
Just commenting that this design decision was by choice in order to attempt to keep dojos more consistent. As in, things should not change unless I do something. If we want to change this, we should reopen another issue.
