### ISSUE TITLE
embryoasm level 5 - modulus bypass

### ISSUE THREAD

**Issue by GordonTTurner** [pwncollege/dojo#164]
While I've already completed the embryoasm challenge, I was redoing it for fish's iteration of pwn.college. During level5, I accidentally performed a wrong instruction, so my file did not successfully compile, and thus when I performed `cat my_executable.bin | /challenge/run`, there was no `my_executable.bin`, so there was no input from cat. However, because the challenge was such that the modulus was 0, I still managed to get the flag, as rax is by default set to zero. As far as I could tell, this only occurs if there is no input to the file, i.e., running `cat $NOTHING | /challenge/run`, but this may also occur if some other code is entered that does not modify rax.
I recreated this issue on the current dojo and could find the same problem there. For reference of recreating the issue, I had the following script to auto-compile my files:

```
#!/bin/bash

level=level${HOSTNAME:28}
gcc -nostdlib --static -o $level.elf $level.s
objcopy --dump-section .text=$level.bin $level.elf
cat $level.bin | /challenge/run
```
So for instance, if my binary was called `level5.s`, I would get `level5.elf` and `level5.bin`. But if `level5.s` fails to compile or does not exist, the final command has no output for cat and therefore no input to the challenge.

**Comment by ConnorNelson** [comment]
Fixed in https://github.com/pwncollege/fundamentals-dojo/commit/cad3268ffcca9b4d462b248c9fdded16dac03766

Thanks for pointing it out. The issue was that sometimes the solution can be 0, which rax is initialized to by default.
