### ISSUE TITLE
SECURITY ISSUE - Flask Debugger Shell in Production

### ISSUE THREAD

**Issue by ConnorNelson** [pwncollege/dojo#165]
Somehow on full restart, a flask debugger shell can become accessible.

This would have to stem from:

```
    command: >
      /bin/sh -c '[ "$DOJO_ENV" != "development" ] &&
                  ./docker-entrypoint.sh  ||
                  FLASK_ENV=development WERKZEUG_DEBUG_PIN=off flask run --host 0.0.0.0 --port 8000'
```

However, it shouldn't be possible, because in the worst case where `"$DOJO_ENV"` is empty, it's still not `"development"`, and so normal production-mode should run.

How did this happen?

**Comment by ConnorNelson** [comment]
In `script/container-setup.sh.`:

```sh
#!/bin/sh

DOJO_DIR=/opt/pwn.college

>> $DOJO_DIR/data/config.env

> $DOJO_DIR/data/.config.env
define () {
    name="$1"
    default="$2"
    re="^${name}=\K.*"
    current="$(env | grep -oP ${re})"
    defined="$(grep -oP ${re} $DOJO_DIR/data/config.env)"
    value="${current:-${defined:-$default}}"
    echo "${name}=${value}" >> $DOJO_DIR/data/.config.env
}
define DOJO_HOST localhost.pwn.college
define DOJO_ENV development
define DOJO_CHALLENGE challenge-minimal
define SECRET_KEY $(openssl rand -hex 16)
define DOCKER_PSLR $(openssl rand -hex 16)
define DISCORD_CLIENT_ID
define DISCORD_CLIENT_SECRET
define DISCORD_BOT_TOKEN
define DISCORD_GUILD_ID
mv $DOJO_DIR/data/.config.env $DOJO_DIR/data/config.env
. $DOJO_DIR/data/config.env
```

This could also be related, especially with the new `development` default for `DOJO_ENV`. However, this should just set the *default* value, which should only happen if a value is not already set. In rebooting, this value should already be set (to `"production"`).

**Comment by Scoder12** [comment]
Could it be that define function? It seems slightly jank, although I don't see anything obviously wrong with it...
Does rolling everything back fix things?
