### ISSUE TITLE
Delete deprecated Dojos Challenges.

### ISSUE THREAD

**Issue by noobone123** [pwncollege/dojo#167]
Hello, I was very impressed by the design of the dojo, so I plan to teaching my course using the dojo. 
However, I have encountered an issue that I cannot find any interface to delete deprecated dojo / module / challenge (of course, the admin panel of ctfd can delete challenge). 
Currently, my approach is using the `dojo db` to enter the database command line and operate the database directly, but I think this is very inelegant. Do you have any suggestions?

Thank You.

**Comment by ConnorNelson** [comment]
The simple answer is that we don't have an "elegant" interface for deleting dojos/modules/challenges.

It hasn't been a priority feature, and furthermore, we haven't had a use case for it. Instead we prefer to archive deprecated content into the archive dojo. This however, also requires manual database queries.
