### ISSUE TITLE
Feature request: support descriptions via `README.md`

### ISSUE THREAD

**Issue by zardus** [pwncollege/dojo#171]
Descriptions in the yml get rather unwieldy. It'd be good to have the option, in the absence of an explicit `description`, of grabbing it from the appropriate `README.md`

For a dojo: `README.md`
For a module: `module/README.md`
For a level: `module/level/README.md`

**Comment by mudongliang** [comment]
This is also a request from students in our course. One simple description in the yaml file is not enough for students at all levels.

**Comment by zardus** [comment]
We support descriptions through DESCRIPTION.md for the dojo, modules, and levels. This is a recent development as of about a month ago, but check out the example dojo for an example: https://github.com/pwncollege/example-dojoOn Dec 27, 2023, at 9:07 PM, Dongliang Mu ***@***.***> wrote:﻿
This is also a request from students in our course. One simple description in the yaml file is not enough for students at all levels.

**Comment by mudongliang** [comment]
Ah, this is great. I've create an issue and replied with example-dojo in our repo.
