### ISSUE TITLE
Deal with dojo source not being owned by root

### ISSUE THREAD

**Issue by Scoder12** [pwncollege/dojo#181]
Currently, if you clone the repo as a non-root user and run the container with the source bind-mounted in as described in the README, the dojo won't accept SSH keys. After some playing around, I found out the issue:
```
Unsafe AuthorizedKeysCommand "/opt/pwn.college/ssh/auth.py": bad ownership or modes for file /opt/pwn.college/ssh/auth.py
```
The authorized keys command is owned by my UID of 1000, which is being passed directly into the container, and `sshd`'s `subprocess` function doesn't like that and refuses to execute it. 

At the minimum, we should detect this situation and fail early and loudly so this isn't tricky to debug. 

A hack to solve this is to use the devcontainer because inside the container the source files are owned by root (although I'd like to avoid this if possible personally).

A workaround solution might be to build a root-owned shell script into the container that directly execs `auth.py` (a symlink wouldn't work here). 

A fully solution might involve some sort of user namespace remapping, which would also solve the less important but still slightly annoying probably of the `./data` directory being owned by UID 0 both in the container and on the local machine. This issue is that user namespace remapping isn't supported by `--privileged` containers. Another solution could be a "copy and chmod" service for source files, although this introduces complexity (risk of being out of sync) and latency.

**Comment by ConnorNelson** [comment]
Solved by #373ab968377d0cd3a4eac89074908f39daadea94.

We put sshd into it's own docker compose service.
