### ISSUE TITLE
Add wechall.net API to dojo for even more internet points

### ISSUE THREAD

**Issue by goreil** [pwncollege/dojo#184]
# Why? Because it's awesome.
[wechall.net](www.wechall.net) is a global ranking list of multiple wargames like OverTheWire, pwnable.kr and Cryptohack.
By gathering points on the respective websites, users get points on a global ranking ladder! By connecting pwn.college to WeChall, there is even more incentive to get flags, since bragging rights are a big motivation (at least to me). It also gives us more exposure on a big wargame forum.

## Steps
The simple procedure is as follows:
1. Implement an API that validates an user. 
2. API that returns the score for a user
3. Contact the admins of [wechall.net](www.wechall.net)

If scores are public then AUTHKEYS are not needed in the APIs.
The API's must be accessible via GET request.

### Step 1 Implement an API that validates an user. 
Example:
`pwn.college/validate?username=%USERNAME%&email=%EMAIL%[&authkey=%AUTHKEY%]`
This script must return simply "1" OR "0",
1:email/username combination exists.
0:combination does not exist or authkey wrong.

### Step 2 API that returns the score for a user
Example:
`pwn.college/score?username=%USERNAME%[&authkey=%AUTHKEY%]`
Your output must contain at least userscore and maxscore. So the output of this script could be like `userscore:maxscore`
Perfect output for this script is: `username:rank:score:maxscore:challssolved:challcount:usercount`

### Step 3 Contact the admins
When the 2 API's are implemented, we can write a mail to the admin.

Email: gizmore@wechall.net
First Name: Christian
>I also want to point out that every single site is a great addition to the challenge scene. Shouts and thanks go out to all the creators! - wechall.net

The detailed requirements can be found on [https://www.wechall.net/join_us](https://www.wechall.net/join_us)

**Comment by gizmore** [comment]
The scoring API should support all supported fields to have the best user and site admin experience.
Like we can track usercount and challcount and support different scores for different challenges.
Of course we do not share our jpgraphs with 3rd parties :P ....

The optimal userscore api format is 6 fields:

                # rank:score:maxscore:challsolved:challcount:usercount
		list($rank, $score, $maxscore, $challsolved, $challcount, $usercount) = explode(':', $result);

For pwn.college, we could abuse the challenge count fields to reflect belts or courses.
Also, new general "trophy" functions would be cool and imaginable, like a PwnC yellow belt trophy :)

greez
giz

**Comment by Zeeshan12340** [comment]
This issue is completed and can be closed. The API has been integrated and is running correctly.
