### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT error when accessing the website

### ISSUE THREAD

**Issue by hardy500** [pwncollege/dojo#189]
When attempting to access the website https://pwn.college/, I encountered an "ERR_CONNECTION_TIMED_OUT" error in my web browser. This issue persists across multiple attempts and on different devices.

I have tested my internet connection, and it seems to be working fine with other websites. 
Clearing browser cache and cookies did not resolve the problem.

Environment
---
OS: MacOS
Browser: Google Chrome

**Comment by adamdoupe** [comment]
Check the announcements in discord, the infrastructure that the dojo runs on had a power outage yesterday, and we're working on getting this running again.
