### ISSUE TITLE
The local deployed infrastructure misses many libraries in the VM

### ISSUE THREAD

**Issue by mudongliang** [pwncollege/dojo#198]
Hi developers,

I deployed pwn.college on my local server. To create my own dojo, I included ROP challenges from software explotation dojo. However, in the VM, the executable misses one external library libcapstone.

```
hacker@return-oriented-programming-level-1-0:/challenge$ ldd babyrop_level1.0 
        linux-vdso.so.1 (0x00007fff7649e000)
        libcapstone.so.5 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa1b5f64000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa1b616a000)
```

I compare the local VM with VM in pwn.college, many libraries in /lib are missing in the local VM, such as libbfd, libcapstone, libctf, libinproctrace, libopcode.

**Comment by zardus** [comment]
Hi, the default container is the minimized one. Change challenge-minimal to challenge in your config.env and you should be good to go On Aug 9, 2023, at 12:45 AM, Dongliang Mu ***@***.***> wrote:﻿
Hi developers,
I deployed pwn.college on my local server. To create my own dojo, I included ROP challenges from software explotation dojo. However, in the VM, the executable misses one external library libcapstone.
***@***.***:/challenge$ ldd babyrop_level1.0 
        linux-vdso.so.1 (0x00007fff7649e000)
        libcapstone.so.5 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa1b5f64000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa1b616a000)

I compare the local VM with VM in pwn.college, many libraries in /lib are missing in the local VM, such as libbfd, libcapstone, libctf, libinproctrace, libopcode.

**Comment by mudongliang** [comment]
Thanks, it works well.
