### ISSUE TITLE
manpages should use less

### ISSUE THREAD

**Issue by ConnorNelson** [pwncollege/dojo#218]
For some reason, man isn't defaulting to `less` as it's pager. We can run `PAGER=less man` to use it, but we should default to `less` as we did before!

**Comment by zardus** [comment]
Could this be a result of my challenge container refactor? The most
relevant piece would be --no-install-recommends to all the apt commands.

**Comment by adamdoupe** [comment]
THIS IS INSANE AND NEEDS TO CHANGE

**Comment by adamdoupe** [comment]
Yan why you keep breaking things
