### ISSUE TITLE
repository already exists as a dojo 

### ISSUE THREAD

**Issue by schuan** [pwncollege/dojo#243]
Dear maintainer, I set up a server with dojo. When I use a **test** user account to create a dojo, e.g., pwncollege/example-dojo, it works fine. When I try to create a dojo using another **test1** user account, it shows the message: " Error: This repository already exists as a dojo ". Is this the right way to create a dojo for everyone?

![Screenshot from 2023-10-19 18-05-18](https://github.com/pwncollege/dojo/assets/5432049/5af8c34d-0452-4f3b-9c85-31f08f8c80b8)

**Comment by ConnorNelson** [comment]
So you probably don't want to create the same dojo multiple times, this would be creating separate dojo instances. And as you see, you can't, a GitHub repo defining a dojo may only be used one time.

If you want to make the dojo accessible to everyone, you need to make that dojo official. Unfortunately we don't have a frontend for this process yet. You can enter the dojo container, and then run `dojo db` to bring up a mysql client. You can determine your dojo's ID with `select id, dojo_id from dojos`. Then, with that `<DOJO_ID>` you can run something like `update dojos set official=1 where dojo_id=<DOJO_ID>`.

**Comment by schuan** [comment]
Thanks for the quick reply. Will try.
