### ISSUE TITLE
Ability to disable practice mode for challenge from yaml

### ISSUE THREAD

**Issue by adamdoupe** [pwncollege/dojo#249]
Sometimes, we want the ability to run a challenge and have students _not_ be able to see the source.

For instance, when teaching web security we want to mimic a situation where the attacker does not have access to source code. Having the practice mode significantly complicates this, as the code can be hidden using permissions, it will then be visible in practice mode (with the user having sudo).

It would also help b/c sometimes practice mode is useless for a challenge and only serves to confuse the users.

**Comment by zardus** [comment]
Done!
