### ISSUE TITLE
VM stop does not stop VM

### ISSUE THREAD

**Issue by robwaz** [pwncollege/dojo#256]
`vm stop` should stop the vm.  It does not.

**Comment by ConnorNelson** [comment]
Can you clarify? I just started the vm, `ps aux` shows qemu is running, and then stopped it, and `ps aux` shows qemu is not running.

**Comment by robwaz** [comment]
Scenario observed was
`vm start`
`vm stop`
`ps aux` and qemu was still running.

I cannot replicate the behavior again.  Closing issue.
