### ISSUE TITLE
change domain 500 error

### ISSUE THREAD

**Issue by ning1022** [pwncollege/dojo#260]
I used my domain named "mydomain.com" to replace the localhost.pwn.college in the data/config.env  `DOJO_HOST=mydomain.com`. and I run the docker command, it show:
```
Nov 24 05:18:22 4aa85a224e60 docker[13120]:  Container sshd  Started
Nov 24 05:18:28 4aa85a224e60 docker[13120]:  Container db  Healthy
Nov 24 05:18:28 4aa85a224e60 systemd[1]: Finished pwn.college docker compose servic
```

but I got 500 error, so I catete the cert using mydomain.com, and replace the cert file in the` /etc/nginx/certs/default.crt`,`/etc/nginx/certs/default.key`.

I open the `~/dojo/data/docker/volumes/pwncollege_conf/_data/default.conf` file . 
```
server {
    server_name mydomain.com;
    http2 on;
    access_log /var/log/nginx/access.log vhost;
    listen 80 ;
    listen 443 ssl ;
    # No certificate found for this vhost, so use the default certificate and
    # return an error code if the user connects via https.
    ssl_certificate /etc/nginx/certs/default.crt;  #mydomain crt 
    ssl_certificate_key /etc/nginx/certs/default.key; #mydomain key
    if ($https) {
        return 500;
    }
    include /etc/nginx/vhost.d/default;
    location / {
        proxy_pass http://mydomain.com;
        set $upstream_keepalive false;
        include /etc/nginx/vhost.d/default_location;
    }
}
```

and add # in the 
```    
#if ($https) {
#        return 500;
#  }

```

the website works.

but we I open challenge ,using the vscode ,the website will become 500 error. and i check the default.conf file ,i recover the old version which did not include #.

how  could i solve this problem?

Thank you.

**Comment by ConnorNelson** [comment]
Is there an error message in the `ctfd` `nginx` or `nginx_certs` container?

**Comment by ning1022** [comment]
i using docker command to restart ctfd twice, it works. very confusing.
