### ISSUE TITLE
Using admin to create dojos, however new users could  not  see the dojos?

### ISSUE THREAD

**Issue by ning1022** [pwncollege/dojo#261]
## Using admin to create dojos, however new users could  not  see the dojos?

I think the dojos have permissions to set, new users don't need to create new dojo again.

Any admin setting or sql command could solve this problem ?

**Comment by Scoder12** [comment]
By default dojos are private so you have to join them to be able to see them. If you want your dojo to be available to all users, you have to make it official. There's no UI for this yet, but you can do it with the following command: 
```console
docker exec -it dojo dojo db -sNe 'UPDATE dojos SET official = 1 WHERE repository = "pwncollege/example-dojo";'
```

**Comment by ning1022** [comment]
Thank you @Scoder12
