### ISSUE TITLE
Use Different Container Secret

### ISSUE THREAD

**Issue by ConnorNelson** [pwncollege/dojo#266]
With the recent changes, we now go off the container id as a container secret. It's not clear this is a good idea, and even further, it doesn't work in cgroup2 (e.g. a modern ubuntu install). This means we can't access our desktop currently on a modern install.

We should inject a secret into the container (/opt/pwn.college/secret, or whatever) and use that instead. Maybe even a `/.metadata` or something, that contains the secret, as well as other information (current user, current challenge, etc).

Then, we use that secret instead, and we also insert the secret as a label on the container, and can therefore get at it without a container fs access.

**Comment by Scoder12** [comment]
not planned?

**Comment by ConnorNelson** [comment]
Should be fixed as of d64c02d6143b9dd795bf8701c006eb4fca1b3004.
