### ISSUE TITLE
Testcases don't run on fork PR?

### ISSUE THREAD

**Issue by zardus** [pwncollege/dojo#350]
It looks like our testcases only run on PRs from this same repo.

**Comment by Scoder12** [comment]
It's to prevent people using your CI minutes to mine crypto. 
> By default, all first-time contributors require approval to run workflows.
> If you are comfortable with running workflows on the pull request branch, return to the Conversation tab, and under "Workflow(s) awaiting approval", click Approve and run.

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by zardus** [comment]
Interesting... https://github.com/pwncollege/dojo/pull/346 doesn't show that option for me on the conversation. I'm guessing that this is because we have `on: push` instead of `pull_request` in https://github.com/pwncollege/dojo/blob/master/.github/workflows/test.yml#L2
