### ISSUE TITLE
Issue on index.html modification

### ISSUE THREAD

**Issue by wumingzhilian** [pwncollege/dojo#353]
I have a problem with modifying index.html.

Before modification:

```
<div class="card-icon">
  <img src="/dojo_theme/static/img/dojo/xxx.svg">
</div>
```

After modification:
```
<div class="card-icon">
  <img src="/themes/dojo_theme/static/img/dojo/xxx.svg">
</div>
```
I added a small path "themes", but when I tried to update using dojo update, the website didn't reflect the changes. I even recreated the CTFd container, but the index.html of the website still wasn't updated. In the end, I had to run a new Dojo container to solve this issue.

How can I fix this bug?

**Comment by adamdoupe** [comment]
I believe you need to go into the CTFd admin side of things to change this. Iirc it’s being cached by CTFd. 

The URL is something like this @wumingzhilian :
https://pwn.college/admin/pages

**Comment by wumingzhilian** [comment]
> I believe you need to go into the CTFd admin side of things to change this. Iirc it’s being cached by CTFd.
> 
> The URL is something like this @wumingzhilian : https://pwn.college/admin/pages

Thanks. I always thought all the modifications were made directly to the index.html file, but it turns out they are within CTFd.

**Comment by zardus** [comment]
index.html *is* imported at dojo start, but unfortunately, `dojo update` doesn't catch that update for some reason

**Comment by mudongliang** [comment]
Any possible solution to cover this in `dojo update`?

**Comment by mudongliang** [comment]
It seems like this issue is fixed by https://github.com/pwncollege/dojo/commit/34fbae79c0d5de19d2638bef6066e0cc40a8d260 by static_override. @wumingzhilian you can close this issue.
