### ISSUE TITLE
Whole website is down.

### ISSUE THREAD

**Issue by austinzwile** [pwncollege/dojo#368]
Okay new issue.

![image](https://github.com/pwncollege/dojo/assets/97855595/d11765dd-920a-4230-87f9-ac2ec00d9e16)

Cleared my cookies and cache and still getting this error. Server-level issue?

Labs weren't starting at first throwing an error "undefined" and now it's completely down. Just want to make sure y'all are aware.

**Comment by robwaz** [comment]
We're almost always aware of when the site goes down as our discord gets quite noisy 😄 .  We're working on it.

**Comment by mudongliang** [comment]
Feel free to join in. Not limited to ASU students. Click on the Chat, and you will get on discord

**Comment by robwaz** [comment]
The bulk of pwn.college conversation occurs on our discord, including challenge discussion. Feel free to join!

https://discord.gg/pwncollege
