### ISSUE TITLE
How should I use the password field in dojo.yml?

### ISSUE THREAD

**Issue by wumingzhilian** [pwncollege/dojo#370]
I don't seem to find any functionality in the webpage to join dojo. It's a little confusing.：）

**Comment by zardus** [comment]
This definitely needs better UI and documentation... Basically, you need to add the password to your join code (after the `/`, in plaintext).

As the dojo url already has at least some level of randomization, the biggest use of the password is:
- gating joining for official dojos
- time-limiting dojo joining (e.g., you can hand out the join code, then change the password later to invalidate the old code)

**Comment by wumingzhilian** [comment]
Thank you, I understand now. It seems that a specific link is required to join.
