### ISSUE TITLE
push some specific package installation to the .init script in some dojos

### ISSUE THREAD

**Issue by mudongliang** [pwncollege/dojo#389]
It seems the challenge container has installed many specific packages related to specific dojos or skill. It is not a good idea to push all the package installation to challenge/Dockerfile, even in full challenge. This will grow the docker image very fast. Maybe we can push some specific package installation to the .init script for some specific dojos.

**Comment by zardus** [comment]
It's definitely possible to give just `/challenge/.init` internet access, and might be something to explore for simple things, but it'll really slow down container starts. Right now, challenges, modules, and dojos already support the `image` attribute (used here: https://github.com/pwncollege/dojo/blob/master/dojo_plugin/api/v1/docker.py#L83), and this can be accomplished through that and either dockerhub or a local docker registry.

**Comment by mudongliang** [comment]
Ah, yes, this defintely slows down starting the challenge, especially bad connection with US Mirror.

**Comment by mudongliang** [comment]
> dojos already support the `image` attribute (used here: https://github.com/pwncollege/dojo/blob/master/dojo_plugin/api/v1/docker.py#L83), and this can be accomplished through that and either dockerhub or a local docker registry.

This is a good feature. Put various images for different aspects.
