### ISSUE TITLE
Make it harder to delete dojos by accident

### ISSUE THREAD

**Issue by zardus** [pwncollege/dojo#445]
We have an awesome way of deleting dojos from the web site thanks to https://github.com/pwncollege/dojo/pull/346, but it's not sufficiently difficult to accidentally delete a dojo. We should have something similar to github's "enter the repository name to confirm" to make things safer.

**Comment by zardus** [comment]
Relevant code: https://github.com/pwncollege/dojo/blob/master/dojo_theme/static/js/dojo/settings.js#L90

**Comment by abhinavk454** [comment]
I want to work with this if it's open to OS contributors.

**Comment by zardus** [comment]
Absolutely open, go for it!

**Comment by JensHouses** [comment]
Added pull request #460 for this issue 🙂

**Comment by JensHouses** [comment]
@zardus this issue can be closed 👍

**Comment by zardus** [comment]
Good catch!
