### ISSUE TITLE
bring back the big + for creating a dojo

### ISSUE THREAD

**Issue by zardus** [pwncollege/dojo#488]
Under the community dojos section, we used to have a `+` card for dojo creation. This got replaced with a link in the main page, and now no one can find the dojo add button.

I think the solution to this is actually to add a new section: `Your Dojos`, with a header that describes that you can create a dojo, the list of dojos for which the logged-in user is an admin, and the `+` button. This would be neat.

**Comment by JensHouses** [comment]
![image](https://github.com/user-attachments/assets/6b395926-5512-4e81-acdc-92906b464545)
as i see this buddy in prod, this Issue can be closed i guess?

**Comment by zardus** [comment]
Good catch!
