### ISSUE TITLE
run.sh script errors

### ISSUE THREAD

**Issue by Tomal-kuet** [pwncollege/dojo#50]
The run.sh script seems to get stuck for me at the following point:
Any suggestion to solve this problem will very helpful. Thank you.

Mar 22 03:18:47 6a57216f5db7 docker-compose[3341]: [2022-03-22T03:18:47.428Z] info  Wrote default config file to ~/.config/code-server/config.yaml
Mar 22 03:18:47 6a57216f5db7 docker-compose[3341]: Installing extensions...
```
Mar 22 03:18:48 6a57216f5db7 docker-compose[3341]: Server returned 404
Mar 22 03:18:48 6a57216f5db7 docker-compose[3341]: [2022-03-22T03:18:48.388Z] error vscode Failed Installing Extensions: ms-python.python
Mar 22 03:18:48 6a57216f5db7 docker-compose[3341]: [2022-03-22T03:18:48.390Z] error vscode Error: Failed Installing Extensions: ms-python.python
Mar 22 03:18:48 6a57216f5db7 docker-compose[3341]:     at O.installExtensions (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:19:42)
Mar 22 03:18:48 6a57216f5db7 docker-compose[3341]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Mar 22 03:18:48 6a57216f5db7 docker-compose[3341]:     at async /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:90861
Mar 22 03:18:48 6a57216f5db7 docker-compose[3341]:     at async M (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:94206)
Mar 22 03:18:48 6a57216f5db7 docker-compose[3341]:     at async process.<anonymous> (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:103823)
Mar 22 03:18:48 6a57216f5db7 docker-compose[3341]: The command '/bin/sh -c mkdir -p /opt/code-server/extensions && code-server --extensions-dir=/opt/code-server/extensions --install-extension ms-python.python' returned a non-zero code: 1
Mar 22 03:18:48 6a57216f5db7 docker-compose[3318]: Service 'challenge' failed to build : Build failed
Mar 22 03:18:48 6a57216f5db7 systemd[1]: pwn.college.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 03:18:48 6a57216f5db7 systemd[1]: pwn.college.service: Failed with result 'exit-code'.
Mar 22 03:18:48 6a57216f5db7 systemd[1]: Failed to start pwn.college docker-compose service.
```

**Comment by ConnorNelson** [comment]
I think I've seen that issue happen randomly once in the past, and I've never had time to properly investigate it. I believe re-running `./run.sh` allowed it to correctly build, and if not that, maybe try rebuilding without the cache.

To do that you would enter the container (`docker exec -it pwn.college bash`), and then force a cacheless build of the challenge container (`docker-compose build --no-cache challenge`).

**Comment by Tomal-kuet** [comment]
I was able to solve this issue by changing the vscode version from `3.10.2` to `4.1.0`, in `challenge/Dockerfile` file.

**Comment by ning1022** [comment]
hi, I also meet this error,

```
root@70cd5b5eb3af:/opt/pwn.college# dojo  wait
Nov 20 07:29:53 70cd5b5eb3af docker[12617]: 10.43     required by: world[openssh-server-pam]
Nov 20 07:29:53 70cd5b5eb3af docker[12617]: 10.43   py3-pip (no such package):
Nov 20 07:29:53 70cd5b5eb3af docker[12617]: 10.43     required by: world[py3-pip]
Nov 20 07:29:53 70cd5b5eb3af docker[12617]: 10.43   python3 (no such package):
Nov 20 07:29:53 70cd5b5eb3af docker[12617]: 10.43     required by: world[python3]
Nov 20 07:29:53 70cd5b5eb3af docker[12617]: ------
Nov 20 07:29:53 70cd5b5eb3af docker[12617]: failed to solve: process "/bin/sh -c apk add --no-cache         python3         py3-pip         openssh-server-pam         docker-cli" did not complete successfully: exit code: 4
Nov 20 07:29:53 70cd5b5eb3af systemd[1]: pwn.college.service: Main process exited, code=exited, status=17/n/a
Nov 20 07:29:53 70cd5b5eb3af systemd[1]: pwn.college.service: Failed with result 'exit-code'.
Nov 20 07:29:53 70cd5b5eb3af systemd[1]: Failed to start pwn.college docker compose service.
```


Any help to   solve this problem?

**Comment by Scoder12** [comment]
My guess of the root cause of this, having worked with scripting VS Code extension installs in the past, is that you are getting hit by Microsoft's relatively aggressive ratelimits. This would explain why re-running the script fixes it. 

The only way I managed to solve it was scripting out manually downloading the VSIX with retries.

**Comment by Scoder12** [comment]
> hi, I also meet this error,
> 
> ```
> root@70cd5b5eb3af:/opt/pwn.college# dojo  wait
> Nov 20 07:29:53 70cd5b5eb3af docker[12617]: 10.43     required by: world[openssh-server-pam]
> Nov 20 07:29:53 70cd5b5eb3af docker[12617]: 10.43   py3-pip (no such package):
> Nov 20 07:29:53 70cd5b5eb3af docker[12617]: 10.43     required by: world[py3-pip]
> Nov 20 07:29:53 70cd5b5eb3af docker[12617]: 10.43   python3 (no such package):
> Nov 20 07:29:53 70cd5b5eb3af docker[12617]: 10.43     required by: world[python3]
> Nov 20 07:29:53 70cd5b5eb3af docker[12617]: ------
> Nov 20 07:29:53 70cd5b5eb3af docker[12617]: failed to solve: process "/bin/sh -c apk add --no-cache         python3         py3-pip         openssh-server-pam         docker-cli" did not complete successfully: exit code: 4
> Nov 20 07:29:53 70cd5b5eb3af systemd[1]: pwn.college.service: Main process exited, code=exited, status=17/n/a
> Nov 20 07:29:53 70cd5b5eb3af systemd[1]: pwn.college.service: Failed with result 'exit-code'.
> Nov 20 07:29:53 70cd5b5eb3af systemd[1]: Failed to start pwn.college docker compose service.
> ```
> 
> Any help to solve this problem?

this is unrelated, should be a separate issue.
