### ISSUE TITLE
Dojo starts, but no webpage.

### ISSUE THREAD

**Issue by Tim-Nosco** [pwncollege/dojo#52]
Log from the `run.sh` script:
```
Mar 25 13:14:56 38edc464d85d docker-compose[3884]: Successfully built 19b8d32b1fa8
Mar 25 13:14:56 38edc464d85d docker-compose[3884]: Successfully tagged pwncollege_ctfd:latest
Mar 25 13:14:56 38edc464d85d docker-compose[3804]: ctfd_db is up-to-date
Mar 25 13:14:56 38edc464d85d docker-compose[3804]: Starting pwncollege_challenge_1 ...
Mar 25 13:14:56 38edc464d85d docker-compose[3804]: Starting ctfd_proxy             ...
Mar 25 13:14:56 38edc464d85d docker-compose[3804]: ctfd_cache is up-to-date
Mar 25 13:14:56 38edc464d85d docker-compose[3804]: ctfd is up-to-date
Mar 25 13:14:57 38edc464d85d docker-compose[3804]: Starting pwncollege_challenge_1 ... done
Mar 25 13:14:57 38edc464d85d docker-compose[3804]: Starting ctfd_proxy             ... done
Mar 25 13:14:57 38edc464d85d docker-compose[3804]: Starting ctfd_acme              ...
Mar 25 13:14:57 38edc464d85d docker-compose[3804]: Starting ctfd_acme              ... done
Mar 25 13:14:57 38edc464d85d systemd[1]: Finished pwn.college docker-compose service.
```
Screenshot from going to `https://localhost`:
![Screenshot from 2022-03-25 09-17-27](https://user-images.githubusercontent.com/3107401/160127999-f712157f-5bd8-4174-9ce6-20d87cbf2396.png)

**Comment by palowashere** [comment]
hey @Tim-Nosco ,

you can fix this by removing a few lines in nginx config when you are running this on localhost. 

### fixing it manually

`docker exec -it pwn.college bash`

once you are inside of this container, run:
`docker exec -it ctfd_proxy bash`

now go to in `/etc/nginx/conf.d/default.conf` and remove these lines (53-59):
```
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        server_tokens off;
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
```
don't forget to restart nginx service:
`service nginx restart`

### fixing it automatically

in `run.sh` you can replace the last line from `docker exec pwn.college logs` to something like 
`docker exec -it pwn.college bash -c "sleep 10; docker exec -it ctfd_proxy bash -c 'sed -i \"53,59d\" /etc/nginx/conf.d/default.conf; sleep 5; service nginx restart'"`

**Comment by ConnorNelson** [comment]
Thanks for the solution! Another option (the option that we take for running locally), is `SETUP_HOSTNAME=localhost.pwn.college`. We have that pointing at 127.0.0.1!
