### ISSUE TITLE
Trouble linking discord to pwn college

### ISSUE THREAD

**Issue by palmerusaf** [pwncollege/dojo#523]
I'm having trouble linking my discord to pwn college. I get to the oauth2 page, but when I press 'Authorize' nothing happens. Furthermore, I checked the browser network tab, and I'm receiving a 400 error. It looks like maybe the channel type is invalid? I've attached screenshots/info below.

## Native User-Agent
- Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0

## Things I've tried but didn't fix
- Deleting all browser data/cookies
- Switching to Chrome
- Changing email from asu.edu to match discord
- Switching user agent to Windows 10/Chrome
![Screenshot from 2024-08-07 13-00-53](https://github.com/user-attachments/assets/14eec37d-de1b-468b-9dce-f136f3d2219c)
![Screenshot from 2024-08-07 13-01-17](https://github.com/user-attachments/assets/205da992-6ca5-4705-a789-f50262e853fb)

**Comment by palmerusaf** [comment]
Was able to link no longer an issue.

**Comment by kimjongbing** [comment]
> Was able to link no longer an issue.

was this solved by just waiting? having the same problem

**Comment by palmerusaf** [comment]
IIRC I was able to linkthe very next day after I created an account.

**Comment by kimjongbing** [comment]
> IIRC I was able to link the very next day after I created an account.

gotcha, i'll wait a day and hope i can link my account. thanks for the reply
