### ISSUE TITLE
`/<dojo>/modules` API endpoint doesn't work

### ISSUE THREAD

**Issue by fpotier** [pwncollege/dojo#527]
Calling the endpoint results in Internal Server Error
For instance:
https://pwn.college/pwncollege_api/v1/dojo/fundamentals/modules

https://github.com/pwncollege/dojo/blob/59b31c64b010f3b4b3f1e70fefc77d832d1a8882/dojo_plugin/api/v1/dojo.py#L155-L166

**Comment by zardus** [comment]
What code even uses that? Is that stale code that we could remove?

**Comment by fpotier** [comment]
I guess no internal code uses it, it's been broken for at least a few months.
I wanted to write an external tool that uses it.

**Comment by JensHouses** [comment]
looks stale to me. as its not even working for month 🤣 we could remove it.
we should maybe check for all unused code anyways

**Comment by zardus** [comment]
I'm definitely not against keeping it if there's a usecase (AND a testcase). @fpotier, do you want to add a testcase? Otherwise, we'll wipe it in the next cleanup :-)

**Comment by fpotier** [comment]
Yeah, I will try to come up with the testcase and a fix
