### ISSUE TITLE
Make sudo behave like sudo

### ISSUE THREAD

**Issue by robwaz** [pwncollege/dojo#582]
It would be great if the dojo's implementation of sudo supported some of real `sudo`'s flags.  

The minimum ask here is `-u` to specify a user.  I know other dojo developers have had the desire to drop privileges in `.init` and execute something as non-root.  This currently can be done with `runuser` or `su -c`, but `sudo` is a reasonable first program to think of to perform this task.

**Comment by supercoolspy** [comment]
In [this](https://github.com/pwncollege/dojo/blob/407f99a555ca718ca065b207f3b216908dd5a4bb/workspace/core/sudo.py) file. I'll probably add it this weekend

**Comment by ConnorNelson** [comment]
Added `--user`/`-u` support in e0e66f6cc9d9cdac3daeef2effb5ccde96588f4b.

If we want to support more of the features, we can implement them when they are requested in a new issue.

**Comment by ConnorNelson** [comment]
> In [this](https://github.com/pwncollege/dojo/blob/407f99a555ca718ca065b207f3b216908dd5a4bb/workspace/core/sudo.py) file. I'll probably add it this weekend

If you want to investigate something this weekend, I'd appreciate your insight on https://github.com/pwncollege/dojo/issues/563!
