### ISSUE TITLE
SSH Into Infrastructure Over Port 22

### ISSUE THREAD

**Issue by ConnorNelson** [pwncollege/dojo#69]
I want to be able to hit the infra over port 22, e.g. `ssh admin@localhost.pwn.college`.

**Comment by Scoder12** [comment]
So we need an escape route from the sshd container into the infra? What do you think of mounting in the docker socket?

**Comment by ConnorNelson** [comment]
I think we had some niche cases for wanting this; but this is probably no longer relevant! I don't think it's actually worth the increased complexity.
