### ISSUE TITLE
Make pwn.college trivial to setup

### ISSUE THREAD

**Issue by ConnorNelson** [pwncollege/dojo#7]
Starting pwn.college should be as simple as `docker-compose up` on a fresh machine with docker and docker-compose installed. We also ideally want to trivially support multiple instances running from the same host.

We can manage the user-setup process with an `env_file` through docker-compose.

---

- [ ] Manage persistent `nosuid` homes

Getting `nosuid` mounts shared across docker containers is VERY tricky. Several hours of testing has produced a potential solution:
```sh
$ docker run -it --rm --mount type=bind,src=/mounts,dst=/mounts,bind-propagation=shared --privileged ubuntu:20.04
$ cd mounts
$ dd if=/dev/zero of=testfs bs=1M count=0 seek=1000
$ mkfs.ext4 -O ^has_journal testfs
$ mount testfs -o nosuid,X-mount.mkdir test
```
This produces a mount on the host which is also nosuid, and which can be mounted into another container as nosuid. This CANNOT be accomplished via a simpler bind mount.

---

- [ ] Manage `/etc/ssh/sshd_config`

We will need to modify, as necessary, this file. This should be relatively easy with mounting it in.
We will also need a container sharing the host's pid namespace:  `sshd rereads its configuration file when it receives a hangup signal, SIGHUP`.

---

- [ ] Manage nginx's `/etc/nginx/vhost.d`

Volume mount from the nginx container. Modify as necessary.
Somehow we need the nginx containers to run if they are not running.

---

- [ ] Manage other system resources

```
sysctl -w kernel.pty.max=1048576
echo core >/proc/sys/kernel/core_pattern
```

Also need to handle:
```
chmod 666 /var/run/docker.sock
```
Though, ideally, we correct this by making the nginx container correctly have access to the socket.

**Comment by zardus** [comment]
Can't we handle the docker socket by doing docker-in-docker instead of docker-compose? I feel that this has a higher chance of success.

Also, insane idea for the suid homes: what if everyone's home dir is a separate file formatted with ext4, and we mount it inside the "outer" docker container before launching the inner one? Another (dubious) benefit of this would be letting students one-click-download their home dirs.

**Comment by zardus** [comment]
Haha, reading that more, I see that the loopback is exactly the route you're taking :-)
