### ISSUE TITLE
Create challenges HTTP server

### ISSUE THREAD

**Issue by ConnorNelson** [pwncollege/dojo#8]
Challenges should be retrieved from a challenges HTTP server. This will allow us to make on-demand challenges publicly accessible. It will also allow the overall system to be more modular and easily extensible. This will help with the use cases of "I just want the challenges" and "I want the infrastructure, but with my own challenges". 

We can make this available at https://challenges.pwn.college/.

The interface could be as simple as 
`/list`-- list all categories
`/<category>/list` -- list all challenges for a category
`/<category>/<challenge>` -- `.tar.gz` of challenge artifacts

We can generate a random-seeded challenge. We can include the seed in the `.tar.gz`'s name, and also embed it in the elf.

It would also be cool to include  `Last-Modified` based on when the particular challenge src was last modified. This could then allow for sweet hotfixed challenge updates.

**Comment by zardus** [comment]
Also, docker-in-docker would let us deploy this easily on the kube
cluster...
