### ISSUE TITLE
Download latest angr-management

### ISSUE THREAD

**Issue by ConnorNelson** [pwncollege/dojo#93]
Blocked by https://github.com/angr/angr-management/issues/732

**Comment by zardus** [comment]
wait, but we had this before this commit: https://github.com/pwncollege/dojo/commit/b5cf4311d67db304f294e1bac3dd72acfbad3c25

**Comment by psiquo** [comment]
Related to this i get an error building 'challenge'.
The report is the following:
```
Sep 19 21:32:21 localhost.pwn.college docker-compose[3279]: gzip: stdin: not in gzip format
Sep 19 21:32:21 localhost.pwn.college docker-compose[3279]: tar: Child died with signal 13
Sep 19 21:32:21 localhost.pwn.college docker-compose[3279]: tar: Error is not recoverable: exiting now
Sep 19 21:32:21 localhost.pwn.college docker-compose[3279]: The command '/bin/sh -c wget -q -O - https://github.com$(curl https://github.com/angr/angr-management/releases | grep angr-management-ubuntu.tar.gz | head -n1 | cut -d'"' -f2) | tar xvz -C /opt' returned a non-zero code: 2
```
I tried also with the referenced commit but could not build due to an `unexpected end of file` from gzip.

**Comment by ConnorNelson** [comment]
> wait, but we had this before this commit: [b5cf431](https://github.com/pwncollege/dojo/commit/b5cf4311d67db304f294e1bac3dd72acfbad3c25)

The issue is that GitHub (with some unknown pattern) decides to include the download link in the web page vs lazily load the link with javascript. Additionally, hardcoding a commit doesn't work since angr-management seems to drop releases. This makes it incredibly annoying to support installing angr-management, and if we can't get a stable way of installing angr-management, we're going to have to drop support.

**Comment by twizmwazin** [comment]
An alternative to installing angr management from our pyinstaller builds would be just to pip install it since we publish to PyPI weekly.

**Comment by zardus** [comment]
sounds great!
